cs412/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('voter_analytics.urls')),
    path("admin/", admin.site.urls),
]

mini_fb/urls.py
from django.urls import path
from .views import (ShowAllProfilesView, ShowProfilePageView, CreateProfileView,
                    CreateStatusMessageView, UpdateProfileView, DeleteStatusMessageView,
                    CreateFriendView, ShowFriendSuggestionsView, ShowNewsFeedView)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authenticate

urlpatterns = [
    path('', ShowAllProfilesView.as_view(), name='show_all_profiles'),
    path('profile/', ShowProfilePageView.as_view(), name='show_own_profile'),
    path('profile/<int:pk>/', ShowProfilePageView.as_view(), name='show_profile'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('status/create_status/', CreateStatusMessageView.as_view(), name='create_status'),
    path('status/<int:pk>/delete/', DeleteStatusMessageView.as_view(), name='delete_status'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('status/delete/<int:pk>/', DeleteStatusMessageView.as_view(), name='delete_status'),
    path('profile/add_friend/<int:other_pk>/', CreateFriendView.as_view(), name='add_friend'),
    path('profile/friend_suggestions/', ShowFriendSuggestionsView.as_view(), name='friend_suggestions'),
    path('profile/news_feed/', ShowNewsFeedView.as_view(), name='news_feed'),
    path('login/', authenticate.LoginView.as_view(template_name='mini_fb/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', authenticate.LogoutView.as_view(template_name='mini_fb/logged_out.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_fb/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User

class Profile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    city = models.CharField(max_length=50)
    email_address = models.EmailField(unique=True)
    pfp_url = models.URLField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_status_messages(self):
        return StatusMessage.objects.filter(profile=self).order_by('-timestamp')

    def get_absolute_url(self):
        return reverse('show_profile', kwargs={'pk': self.pk})

    def get_friends(self):
        friends1 = Friend.objects.filter(profile1=self)
        friends2 = Friend.objects.filter(profile2=self)
        friends3 = []

        for friend in friends1:
            friends3.append(friend.profile2)

        for friend in friends2:
            friends3.append(friend.profile1)

        return friends3

    def get_friend_suggestions(self):
        all_profiles = Profile.objects.exclude(pk=self.pk)
        friend_pks = [friend.pk for friend in self.get_friends()]

        return all_profiles.exclude(pk__in=friend_pks)
    def add_friend(self, other):
        if self == other:
            raise Exception("Adding yourself")
        friendship_exists = Friend.objects.filter((Q(profile1=self) & Q(profile2=other)) | (Q(profile1=other) & Q(profile2=self))).exists()

        if not friendship_exists:
            Friend.objects.create(profile1=self, profile2=other)
        else:
            return

    def get_news_feed(self):
        friends = self.get_friends()
        profiles = friends + [self]

        news_feed = StatusMessage.objects.filter(profile__in=profiles).order_by('-timestamp')
        return news_feed

class StatusMessage(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=500)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.timestamp} - {self.profile.first_name}: {self.message}"

    def get_images(self):
        return Image.objects.filter(status_message=self)

class Image(models.Model):
    image_file = models.ImageField(upload_to='images/')
    status_message = models.ForeignKey(StatusMessage, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.status_message} {self.timestamp}"

class Friend(models.Model):
    profile1 = models.ForeignKey(Profile, related_name='friend_profile1', on_delete=models.CASCADE)
    profile2 = models.ForeignKey(Profile, related_name='friend_profile2', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.profile1} & {self.profile2}"

mini_fb/forms.py
from django import forms
from .models import Profile, StatusMessage

class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'city', 'email_address', 'pfp_url']

class CreateStatusMessageForm(forms.ModelForm):
    class Meta:
        model = StatusMessage
        fields = ['message']

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'email_address', 'pfp_url']

mini_fb/views.py
# mini_fb/views.py

from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Profile, StatusMessage, Image
from .forms import CreateProfileForm, CreateStatusMessageForm, UpdateProfileForm
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

class ShowAllProfilesView(ListView):
    """Shows all profiles"""
    model = Profile
    template_name = 'mini_fb/show_all_profiles.html'
    context_object_name = 'profiles'


class ShowProfilePageView(DetailView):
    model = Profile
    template_name = 'mini_fb/show_profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        if 'pk' in self.kwargs:
            return super().get_object(queryset)
        else:
            return get_object_or_404(Profile, user=self.request.user)


class CreateProfileView(CreateView):
    form_class = CreateProfileForm
    template_name = 'mini_fb/create_profile_form.html'

    def get(self, request, *args, **kwargs):
        profile_form = self.form_class()
        user_form = UserCreationForm()
        return render(request, self.template_name, {
            'profile_form': profile_form,
            'user_form': user_form,
        })

    def post(self, request, *args, **kwargs):
        profile_form = self.form_class(request.POST)
        user_form = UserCreationForm(request.POST)

        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            return redirect('show_own_profile')
        else:
            return render(request, self.template_name, {
                'profile_form': profile_form,
                'user_form': user_form,
            })


class CreateStatusMessageView(LoginRequiredMixin, CreateView):
    model = StatusMessage
    form_class = CreateStatusMessageForm
    template_name = 'mini_fb/create_status_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(Profile, user=self.request.user)
        context['profile'] = profile
        return context

    def form_valid(self, form):
        profile = get_object_or_404(Profile, user=self.request.user)
        form.instance.profile = profile
        response = super().form_valid(form)

        images = self.request.FILES.getlist('images')
        for image in images:
            img = Image(image_file=image, status_message=self.object)
            img.save()

        return response

    def get_success_url(self):
        return reverse('show_profile', kwargs={'pk': self.object.profile.pk})


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateProfileForm
    template_name = 'mini_fb/update_profile_form.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

    def get_success_url(self):
        return reverse('show_profile', kwargs={'pk': self.object.pk})


class DeleteStatusMessageView(LoginRequiredMixin, DeleteView):
    model = StatusMessage
    template_name = 'mini_fb/delete_status_form.html'
    context_object_name = 'status_message'

    def dispatch(self, request, *args, **kwargs):
        status_message = self.get_object()
        if status_message.profile.user != request.user:
            messages.error(request, "You are not authorized to delete this status message.")
            return redirect('show_profile', pk=status_message.profile.pk)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('show_own_profile')


class CreateFriendView(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        other_pk = self.kwargs.get('other_pk')
        profile = get_object_or_404(Profile, user=request.user)
        other_profile = get_object_or_404(Profile, pk=other_pk)

        try:
            profile.add_friend(other_profile)
            messages.success(request, f"You are now friends with {other_profile.first_name} {other_profile.last_name}.")
        except Exception as e:
            messages.error(request, str(e))

        return redirect('show_profile', pk=other_profile.pk)


class ShowFriendSuggestionsView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'mini_fb/friend_suggestions.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['friend_suggestions'] = context['profile'].get_friend_suggestions()
        return context


class ShowNewsFeedView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'mini_fb/news_feed.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_feed'] = context['profile'].get_news_feed()
        return context

mini_fb/templates/mini_fb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mini Facebook</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header>
        <h1><a href="{% url 'show_all_profiles' %}">Mini Facebook</a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'show_own_profile' %}">My Profile</a></li>
                    <li>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'create_profile' %}">Create New Profile</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {% if user.is_authenticated and user.profile %}
        <p>
            <a href="{% url 'news_feed' %}">News Feed</a>
        </p>
    {% endif %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
    {% endblock %}

    <footer>
        <p>&copy; 2024 Mini Facebook</p>
    </footer>
</body>
</html>

mini_fb/templates/mini_fb/create_profile_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Create Profile</h2>
<form method="post">
    {% csrf_token %}
    <h3>User Infor</h3>
    {{ user_form.as_p }}
    <h3>Profile Info</h3>
    {{ profile_form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

mini_fb/templates/mini_fb/create_status_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Create Status Message</h2>
<form method="POST" enctype="multipart/form-data" action="{% url 'create_status' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="images">Upload Images:</label>
    <input type="file" name="images" id="images" multiple>
    <br><br>
    <button type="submit">Submit</button>
</form>
{% endblock %}

mini_fb/templates/mini_fb/delete_status_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Delete Status Message</h2>

<p>{{ status_message.message }}</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

<form method="get" action="{% url 'show_own_profile' %}">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

mini_fb/templates/mini_fb/friend_suggestions.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Friend Suggestions</h2>

{% if friend_suggestions %}
    <ul>
        {% for suggestion in friend_suggestions %}
            <li>
                <a href="{% url 'show_profile' pk=suggestion.pk %}">
                    {{ suggestion.first_name }} {{ suggestion.last_name }}
                </a>
                <a href="{% url 'add_friend' other_pk=suggestion.pk %}">Add Friend</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Friend Suggestions</p>
{% endif %}

<p>
    <a href="{% url 'show_own_profile' %}">Back to Profile</a>
</p>
{% endblock %}

mini_fb/templates/mini_fb/logged_out.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>You logged out</h2>
<p><a href="{% url 'login' %}">Log in</a></p>
{% endblock %}

mini_fb/templates/mini_fb/login.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{% url 'show_all_profiles' %}">
    <button type="submit">Login</button>
</form>
{% endblock %}

mini_fb/templates/mini_fb/news_feed.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>News Feed for {{ profile.first_name }} {{ profile.last_name }}</h2>

{% if news_feed %}
    <ul>
        {% for status in news_feed %}
            <li>
                <div class="status-message">
                    <div class="profile-info">
                        <img src="{{ status.profile.pfp_url }}" width="50" height="50">
                        <a href="{% url 'show_profile' pk=status.profile.pk %}">
                            {{ status.profile.first_name }} {{ status.profile.last_name }}
                        </a>
                    </div>
                    <p>{{ status.message }}</p>
                    <p><em>{{ status.timestamp|date:"SHORT_DATETIME_FORMAT" }}</em></p>
                    {% for img in status.get_images %}
                        <div>
                            <img src="{{ img.image_file.url }}" width="150">
                        </div>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No messages</p>
{% endif %}

<p>
    <a href="{% url 'show_own_profile' %}">Back to Profile</a>
</p>
{% endblock %}

mini_fb/templates/mini_fb/show_all_profiles.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>All Profiles</h2>
<table>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>City</th>
        <th>Profile Image</th>
    </tr>
    {% for profile in profiles %}
    <tr>
        <td><a href="{% url 'show_profile' pk=profile.pk %}">{{ profile.first_name }}</a></td>
        <td><a href="{% url 'show_profile' pk=profile.pk %}">{{ profile.last_name }}</a></td>
        <td>{{ profile.city }}</td>
        <td>
            <a href="{% url 'show_profile' pk=profile.pk %}">
                <img src="{{ profile.pfp_url }}" width="100" height="100">
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

mini_fb/templates/mini_fb/show_profile.html
<!-- show_profile.html -->

{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>{{ profile.first_name }} {{ profile.last_name }}</h2>

{% if user.is_authenticated and profile.user == user %}
    <p><a href="{% url 'update_profile' %}">Update Profile</a></p>
{% endif %}

<img src="{{ profile.pfp_url }}" width="600" height="600">

<table>
    <tr>
        <th>First Name:</th>
        <td>{{ profile.first_name }}</td>
    </tr>
    <tr>
        <th>Last Name:</th>
        <td>{{ profile.last_name }}</td>
    </tr>
    <tr>
        <th>City:</th>
        <td>{{ profile.city }}</td>
    </tr>
</table>

<h3>Friends</h3>
{% if profile.get_friends %}
    <ul>
        {% for friend in profile.get_friends %}
            <li>
                <a href="{% url 'show_profile' pk=friend.pk %}">
                    {{ friend.first_name }} {{ friend.last_name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No friends</p>
{% endif %}

<h3>Status Messages</h3>
<ul>
    {% for status in profile.get_status_messages %}
        <li>
            <strong>{{ status.timestamp|date:"SHORT_DATETIME_FORMAT" }}</strong>: {{ status.message }}
            {% for img in status.get_images %}
                <div>
                    <img src="{{ img.image_file.url }}" width="200">
                </div>
            {% endfor %}
            {% if user.is_authenticated and profile.user == user %}
                <p>
                    <a href="{% url 'delete_status' pk=status.pk %}">Delete</a>
                </p>
            {% endif %}
        </li>
    {% empty %}
        <li>No status messages</li>
    {% endfor %}
</ul>

{% if user.is_authenticated and profile.user == user %}
    <p>
        <a href="{% url 'create_status' %}">Create Status</a>
    </p>
    <p>
        <a href="{% url 'friend_suggestions' %}">See Friend Suggestions</a>
    </p>
{% endif %}

{% endblock %}

mini_fb/templates/mini_fb/update_profile_form.html
{% extends 'mini_fb/base.html' %}

{% block content %}
<h2>Update Profile</h2>

<form method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th><label for="id_city">City:</label></th>
            <td>{{ form.city }}</td>
        </tr>
        <tr>
            <th><label for="id_email_address">Email:</label></th>
            <td>{{ form.email_address }}</td>
        </tr>
        <tr>
            <th><label for="id_pfp_url">Profile Photo:</label></th>
            <td>{{ form.pfp_url }}</td>
        </tr>
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}